url: "https://milanrosko.com"
baseurl: ""
title: "Milan Rosko â€” Logician & Designer"
description: "Research in constructive logic and theory of computation."
keywords: "Constructive Logic, Proof Theory, Realizability, Information design"
author: "Milan Rosko"
og_image: "/aux/1200x630.png"
